yarnPath: .yarn/releases/yarn-berry.js

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: '@yarnpkg/plugin-typescript'

packageExtensions:
  xo@*:
    dependencies:
      eslint-config-xo-react: '^0.23.0'
      eslint-plugin-react: '^7.17.0'
      eslint-plugin-react-hooks: '^3.0.0'
    peerDependencies:
      webpack: '*'
